Repository paketo-buildpacks/spring-boot, pull requests merged in 2022-03, with the labels that each got.

#191 add build configuration env "BP_SPRING_CLOUD_BINDINGS_ENABLED"
  README.md
  boot/build.go
  boot/build_test.go
  buildpack.toml
Labels: semver:minor, type:enhancement

#193 Polishing around new Spring Cloud Bindings changes
  README.md
  boot/build.go
  boot/build_test.go
  buildpack.toml
  helper/spring_cloud_bindings.go
  helper/spring_cloud_bindings_test.go
Labels: semver:patch, type:enhancement

#200 Fixes inaccuracies in the documentation for disabling Spring Cloud Bindings
  README.md
  buildpack.toml
Labels: type:documentation, semver:patch
