Repository paketo-buildpacks/spring-boot, pull requests merged in 2024-05, with the labels that each got.

#427 Spring Boot CDS support
  .gitignore
  README.md
  boot/build.go
  boot/build_test.go
  boot/detect.go
  boot/init_test.go
  boot/spring_cloud_bindings.go
  boot/spring_performance.go
  boot/spring_performance_test.go
  boot/testdata/cds/spring-app-3.3-no-dependencies.jar
  buildpack.toml
  cmd/helper/main.go
  cmd/main/unpack_test.go
  go.mod
  go.sum
  helper/init_test.go
  helper/spring_cloud_bindings.go
  helper/spring_cloud_bindings_test.go
  helper/spring_performance.go
  helper/spring_performance_test.go
  scripts/build.sh
Labels: semver:minor, type:enhancement

#475 correctly handles case where no jar was found
  boot/build.go
  boot/build_test.go
Labels: type:bug, semver:patch

#476 Document CDS_TRAINING_JAVA_TOOL_OPTIONS
  README.md
Labels: type:documentation, semver:patch

#484 Fix #481: Rely on JRE_HOME for Java location
  boot/spring_performance.go
  boot/spring_performance_test.go
Labels: type:bug, semver:patch
